    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/install-tools@v1.2.0

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1.2.0
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: MojaStrona_Wersjonowanie
          solution-output-file: out/solution.zip

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1.2.0
        with:
          solution-file: out/solution.zip
          solution-folder: solutions/MojaStrona_Wersjonowanie
          solution-type: Unmanaged

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatyczny eksport wersji rozwiÄ…zania"
          git push
